namespace Nadlan.Models.Enums
{
    public enum Accounts
    {
        Rent = 1,
        Management = 2,
        ProjectManagement = 3,
        MaintenanceMiscellaneous = 4,
        Tax = 5,
        RenovationMiscellaneous = 6,
        Legal = 7,
        Registration = 8,
        Accountancy = 9,
        AgencyFees = 10,
        PurchaseMiscellaneous = 11,
        ApartmentCost = 12,
        Investment = 13,
        Mortgage = 14,
        Housgeld = 15,
        PersonalAdministration = 16,
        RenovationContractor = 17,
        NewTenantMiscellaneous = 18,
        TenatExpenses = 19,
        Amenities = 20,
        Mortgage_Interest = 21,
        Mortgage_Payment = 22,
        TaxEstimation = 50,
        Distribution = 100,
        SecurityDeposit = 198,
        Business = 200,
        Balance = 201,
        CashWithdrawal = 202,
        Bonus = 300,
    }
}
